#!/usr/bin/ruby

class Inputer
  def initialize(default=false)
    @defaultprompt = default
  end

  def character()
    begin
      system("stty raw -echo")
      print @defaultprompt if @defaultprompt
      str = STDIN.getc
    ensure
      system("stty -raw echo")
    end
    return str.chr
  end
end
